//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int Id { get; set; }
        public string CarName { get; set; }
        public string CarModel { get; set; }
        public string RegisterId { get; set; }
        public string Reputition { get; set; }
        public decimal? ChargePercent { get; set; }
        public decimal? Lat { get; set; }
        public decimal? Long { get; set; }
        public decimal? TargetLat { get; set; }
        public decimal? TargetLong { get; set; }
        public string IsReserved { get; set; }
        public string IsPaired { get; set; }
        public Nullable<int> PairedCarId { get; set; }
    }
}
